drive = "/dev/sda" # Drive to install to
root_url = "http://151.232.8.86:5000/root.img" # Root image to download
filesystem = "btrfs" # Filesystem layout
user = "maria" # username to create (you will be prompted for a password if set)
applications = "recommended" # package set to install (look in system.toml to find and edit them)